

object builder {
  def main(args: Array[String]):Unit = {
      //this file and function is designed to just feed data into the data base from a csv file
      //it makes usernamename and generates a password from a number I make
      //player names taken from https://raw.githubusercontent.com/hadley/data-baby-names/master/baby-names.csv 
      //monster names are generated by: https://www.fantasynamegenerators.com/monster-names.php
      
        
  }
}
